# Use a imagem oficial do Node.js 21.5.0
FROM node:21.0.0

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json . 

# Instale o Angular CLI globalmente
RUN npm cache clean --force    
RUN npm install -g @angular/cli
RUN npm install -g nodemon

COPY . .

EXPOSE 4200
CMD ["nodemon", "--legacy-watch"]