version: '3'
services:
  backend:
    build:
      context: .
    restart: always
    container_name: backend_ciee
    volumes:
      - ./backend:/app:rw
    ports:
      - 8080:8080
    networks:
      - netCieeLocal  
    # command: /bin/sh -c "mvn package && java -jar target/kanban-1.0-SNAPSHOT.jar"

  frontend:
    build:
      context: ./frontend
    restart: always
    container_name: frontend_ciee
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app:rw
      - node_modules:/app/node_modules:rw
    networks:
      - netCieeLocal
    command: /bin/sh -c "npm install && ng serve --port 4200 --host 0.0.0.0"

volumes:
  node_modules:

networks:
  netCieeLocal:
    driver: bridge
